# Project information
site_name: 'Experiences To Do'
site_description: 'Experiences To Do in a country, place, city a location of your choice! Check for the available experiences!'
site_author: 'Antonio Feijao UK'

site_url: 'https://www.experiencestodo.com/'

repo_name: 'www.experiencestodo.com'
repo_url: 'https://github.com/AntonioFeijaoUK/www.experiencestodo.com'

# Theme
theme:
  name: 'material'
  language: 'en'
  logo:
    icon: 'cloud_done'
  favicon: '/images/favicon.ico'
  palette:
    primary: 'green'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true

# Customization    
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'linkedin'
      link: 'https://linkedin.com/in/antoniofeijaouk/'
    - type: 'github'
      link: 'https://github.com/antoniofeijaouk/'
    - type: 'twitter'
      link: 'https://twitter.com/antoniofeijaouk/'
    - type: 'instagram'
      link: 'https://www.instagram.com/AntonioFeijaoUK/'
  disqus: 'antoniocloud'
  search:
    tokenizer: '[\s\-\.]+'

extra_css:
  - 'assets/stylesheets/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - fontawesome_markdown

# Copyright
copyright: 'Copyright &copy; 2019 Antonio Feijao UK'
