# Project information
site_name: 'Experiences 4 You'
site_description: '"Experiences 4 You" in a country, place, city a location of your choice! Check for the available experiences!'
site_author: 'Antonio Feijao UK'

site_url: 'https://www.experiences4you.com/'

repo_name: www.experiences4you.com
repo_url: 'https://github.com/AntonioFeijaoUK/www.experiences4you.com'


# Theme
theme:
  name: 'material'
  language: 'en'
  logo:
    icon: 'cloud_done'
  favicon: '/images/favicon.ico'
  palette:
    primary: 'green'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true

# Customization    
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'linkedin'
      link: 'https://linkedin.com/in/antoniofeijaouk/'
    - type: 'github'
      link: 'https://github.com/antoniofeijaouk/'
    - type: 'twitter'
      link: 'https://twitter.com/antoniofeijaouk/'
    - type: 'instagram'
      link: 'https://www.instagram.com/AntonioFeijaoUK/'
  
  disqus: 'experiences4you'
  
  google_analytics:
    - 'UA-145415820-1'
    - 'auto'
  
  search:
    tokenizer: '[\s\-\.]+'

extra_css:
  - '/assets/stylesheets/extras.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - fontawesome_markdown

# Copyright
copyright: 'Copyright &copy; 2019 Antonio Feijao UK'
